"""Initial relational portfolio schema"""
from alembic import op
import sqlalchemy as sa
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_ip_created', 'contact_messages', ['ip_hash', 'created_at'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('repository', sa.String(length=200), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=7), nullable=False),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rate_limit_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experience_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_highlights_experience_id'), 'experience_highlights', ['experience_id'], unique=False)
    op.create_table('experience_technologies',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('experience_id', 'technology_id')
    )
    op.create_table('project_architecture_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key')
    )
    op.create_index(op.f('ix_project_architecture_nodes_project_id'), 'project_architecture_nodes', ['project_id'], unique=False)
    op.create_table('project_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_features_project_id'), 'project_features', ['project_id'], unique=False)
    op.create_table('project_technologies',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'technology_id')
    )
    op.create_table('technology_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_usages_technology_id'), 'technology_usages', ['technology_id'], unique=False)
    op.create_table('project_architecture_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['project_architecture_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['project_architecture_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_architecture_edges_project_id'), 'project_architecture_edges', ['project_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_architecture_edges_project_id'), table_name='project_architecture_edges')
    op.drop_table('project_architecture_edges')
    op.drop_index(op.f('ix_technology_usages_technology_id'), table_name='technology_usages')
    op.drop_table('technology_usages')
    op.drop_table('project_technologies')
    op.drop_index(op.f('ix_project_features_project_id'), table_name='project_features')
    op.drop_table('project_features')
    op.drop_index(op.f('ix_project_architecture_nodes_project_id'), table_name='project_architecture_nodes')
    op.drop_table('project_architecture_nodes')
    op.drop_table('experience_technologies')
    op.drop_index(op.f('ix_experience_highlights_experience_id'), table_name='experience_highlights')
    op.drop_table('experience_highlights')
    op.drop_table('technologies')
    op.drop_table('rate_limit_buckets')
    op.drop_table('projects')
    op.drop_table('experiences')
    op.drop_table('contributions')
    op.drop_index('ix_contact_ip_created', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_table('certifications')
    # ### end Alembic commands ###
